const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //admin:
    FETCH_GENDER_START:'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS:'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAIDED:'FETCH_GENDER_FAIDED',

    CREATE_USER_SUCCES:'CREATE_USER_SUCCES',
    CREATE_USER_FAILED:'CREATE_USER_FAILED',

    DELETE_USER_SUCCES:'DELETE_USER_SUCCES',
    DELETE_USER_FAILED:'DELETE_USER_FAILED',
    
    EDIT_USER_SUCCES:'EDIT_USER_SUCCES',
    EDIT_USER_FAILED:'EDIT_USER_FAILED',

    FETCH_ALL_USERS_FAIDED:'FETCH_ALL_USERS_FAIDED',
    FETCH_ALL_USERS_SUCCESS:'FETCH_ALL_USERS_SUCCESS',

   
})

export default actionTypes;